# serverless.yml

service: opus-db-graphql
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  serverless-offline:
    port: 4000
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
      - http:
          path: /graphql
          method: post
          credentials: true
          cors: true
      - http:
          path: /graphql
          method: get
          cors: true
  ping:
    handler: handler.ping
    events:
      - http:
          path: /ping
          method: get
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: /
          method: get
