# serverless.yml

service: opus-db-graphql
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          credentials: true
          preflightContinue: true
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - apollographql-client-name
              - apollographql-client-version
      - http:
          path: graphql
          method: get
          cors: true
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: /
          method: get
